### ISSUE TITLE
Modificar estilo de la página - Crear RID Theme

### ISSUE THREAD

**Issue by mesanhueza** [crai-unrn/DSpace#11]
Es necesario crear un estilo personalizado para la página del RID.

### Tareas necesarias

- [x] Migrar el RID de la versión 5.4 a la 6.3 (#34)

### Tareas generales

- [x] Modificar footer (#10)
- [x] Modificar header (#12)
- [x] Modificar vista de las Políticas del RID (#14)
- [x] Crear sección de preguntas frecuentes (#13)
- [x] Modificar Home (#16)
- [x] Modificar login y registro de cuenta (#20)
- [x] Modificar páginas de post-registro de usuario
- [x] Modificar vista de Comunidades y colecciones (#22)
- [x] Modificar página de búsqueda
- [x] Modificar página del ítem (No es necesario por ahora)
- [x] Modificar página de la Comunidad (#38)
- [x] Modificar página de la Colección (#40)
