### ISSUE TITLE
LA Referencia: Configurar MATOMO Tracking

### ISSUE THREAD

**Issue by mesanhueza** [crai-unrn/DSpace#92]
[La Red Federada de Repositorios Institucionales de Publicaciones Científicas](http://www.lareferencia.info/es/), o simplemente LA Referencia, es una red latinoamericana de repositorios de acceso abierto. Por medio de sus servicios, apoya las estrategias nacionales de Acceso Abierto en América Latina mediante una plataforma con estándares de interoperabilidad, compartiendo y dando visibilidad a la producción científica generada en las instituciones de educación superior y de investigación científica.

LA Referencia, junto a [OpenAIRE](https://www.openaire.eu/), está llevando a cabo una prueba piloto de estadísticas distribuidas en el cual Argentina participará junto con otros países de Latinoamerica.

> Nota: El día 02-03-2020 se realizó una reunión virtual, en la cual Lautaro Matas (LA Referencia) presentó el piloto, sus alcances, el resultado esperado y los requisitos de participación.

### Requisitos para la prueba piloto
- Usar DSpace
- Contar con un ID de [OpenDOAR](https://v2.sherpa.ac.uk/opendoar/)

### Documentación de LA Referencia
- Repositorio Github de [dspace-stats-collector](https://github.com/lareferencia/dspace-stats-collector): Implementación de una alternativa ligera, fácil de instalar y de solo lectura para un recopilador de datos de uso de DSpace compatible con la infraestructura de estadísticas de uso de Matomo y OpenAire.
- Guía de instalación de la [API anterior](https://dspace-stats-collector.readthedocs.io/en/latest/installation.html)
- [Tracking HTTP API](https://developer.matomo.org/api-reference/tracking-api)

### Tareas
- [x] Obtener un ID de OpenDOAR
    > **(!) IMPORTANTE (!)**: el ID de OpenDOAR del RID es 4369. Para más información ir a <https://v2.sherpa.ac.uk/id/repository/4369>
- [x] Consultar con el departamento de Soporte Técnico de la UNRN por la ejecución de dicha API y sus posibles consecuencias en el servidor.
- [x] Informar al SNRD (Alberto Apollaro o Paola Azrilevich) la intención de formar parte del piloto y solicitar los parámetros de la API
- [x] Documentar el procedimiento a fin de ayudar o dar soporte a otra institución.
    > Ver [documentación](https://github.com/crai-unrn/DSpace/wiki/Configurar-MATOMO-Traking-para-LA-Referencia)
- [ ] Instalar y probar el paquete dspace-stats-collector
- [ ] Compartir dicha documentación el el grupo de [DSpace de las universidades](https://groups.google.com/a/sedici.unlp.edu.ar/forum/#!forum/dspace)
